# Generated by Django 4.0.6 on 2022-07-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0003_character_added_by_movie_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='movies_app.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
